---
title: "Number of car accidents between 2020 and 2022 in Poland per County"
author: "kp-muszynski"
output: html_document

---


```{r setup, include=FALSE, error=FALSE, warning = FALSE, message=FALSE}

# read necessary libraries
library(rgdal)
library(rgeos)
library(ggplot2)
library(dplyr)
library(plotly)
library(rstudioapi)

# set working directory to the same directory as R script
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

# read voivodeship map from Shp file for contour
mapa_w<-readOGR("PRG_jednostki_administracyjne_2022/A01_Granice_wojewodztw.shp")
mapa_woj<-fortify(mapa_w,region="JPT_KOD_JE")

# read County map from Shp file
mapa<-readOGR("PRG_jednostki_administracyjne_2022/A02_Granice_powiatow.shp")
mapa_nazwy <- mapa@data %>% select(JPT_KOD_JE, JPT_NAZWA_)
mapa_df<-fortify(mapa,region="JPT_KOD_JE")
mapa_df<-left_join(mapa_df, mapa_nazwy, by=c("id"="JPT_KOD_JE"))

# reading car accidents data per County
wypadki<-read.csv2("wypadki.txt")
wypadki<-wypadki %>% mutate(ID_ini = substr(as.character(Kod),1,nchar(Kod)-3),
                   ID = ifelse(nchar(ID_ini)==3,paste("0",ID_ini,sep=""),ID_ini)) %>% select(-c("Kod","ID_ini"))

# joining car accidents to map data
mapa2<-mapa_df %>% left_join(wypadki, by=c("id"="ID"))%>%rename(County=JPT_NAZWA_,
                                                                Accidents_2022=y2022,
                                                                Accidents_2021=y2021,
                                                                Accidents_2020=y2020,
                                                                Voivodeship=woj)
a<-min(wypadki$y2022)
b<-max(wypadki$y2022)
# a=min(wypadki[[var_y]])
# mapa2<-rename(mapa2,"{var_y}" := Wypadki)
```

<br/><br/>
<br/><br/>

```{r mapa, echo = FALSE, warning = FALSE, message=FALSE, fig.align='left', out.width = '110%', out.height='110%'}

# preparing plot
  
mapa_plot<-ggplot(mapa2) + 
  geom_polygon(aes(long, lat, group=group, County=County, Voivodeship=Voivodeship, fill=Accidents_2022, Accidents_2021=Accidents_2021, Accidents_2020=Accidents_2020), color="gray", show.legend = FALSE) + 
  geom_path(data=mapa_woj, aes(long, lat, group=group), linetype="longdash", color="black", show.legend = FALSE) + 
  coord_map() + 
  theme_void() + 
  scale_fill_gradient2(low = "green",mid="orange", high="red", limits=c(a,b), midpoint=375) + 
  ggtitle(label="Colored with accidents in 2022") + 
  theme(plot.title = element_text(size=14, face="bold.italic", hjust=0.5))

# making plotly 
mapa_plotly<-ggplotly(mapa_plot,tooltip=c("County","Voivodeship","Accidents_2022","Accidents_2021","Accidents_2020")) %>%
  layout(yaxis = list(showline = FALSE),xaxis = list(showline = FALSE), width = 1000, height=500)

# displaying plotly for the knit
mapa_plotly
  
```
